apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment02
  namespace: gitops
  labels:
    app: nginx02
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx02
  template:
    metadata:
      labels:
        app: nginx02
    spec:
      containers:
      - name: nginx02
        image: nginx:1.14.2
        ports:
        - containerPort: 80
